FROM faizanscuelogic/python-2.7
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH "/usr/local/bin/python"
RUN mkdir /private_message
WORKDIR /private_message
RUN apt-get -y update
RUN apt-get -y install curl wget make gcc build-essential
RUN apt-get install -y python-dev
RUN apt-get install -y supervisor
RUN apt-get install -y nginx
RUN pip install gunicorn
RUN pip install setproctitle
ADD requirements.txt /private_message/
RUN pip install -r requirements.txt 
ADD . /private_message/
COPY docker-entrypoint.sh /private_message/
RUN chmod u+x docker-entrypoint.sh
RUN chmod u+x bin/gunicorn_start  
COPY message.conf /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/message.conf /etc/nginx/sites-enabled
COPY message_supervisor.conf  /etc/supervisor/conf.d/
EXPOSE 80
RUN mkdir -p /private_message/logs
RUN mkdir -p /static
RUN mkdir -p /private_message/static
RUN chmod -R 777 /static
RUN touch /private_message/logs/gunicorn_supervisor.log
RUN python manage.py migrate
ENTRYPOINT ["bash", "/private_message/docker-entrypoint.sh"]
