# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_mysql.models.ListCharField(models.IntegerField(), max_length=12600, size=100)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Others', 'OTHERS')], max_length=20, null=True)),
                ('birthday', models.DateField(null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='agent_picture/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('account', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.CharField(blank=True, max_length=10, null=True)),
                ('category', django_mysql.models.ListCharField(models.IntegerField(), max_length=12600, size=100)),
                ('assendents', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('total_resolved_issues', models.IntegerField(default=0)),
                ('total_open_issue', models.IntegerField(default=0)),
                ('total_resolved_ticket_heat_index', models.IntegerField(default=0)),
                ('average_resolved_ticket_heat_index', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'agent',
            },
        ),
    ]
