 FROM faizanscuelogic/python-2.7
 ENV PYTHONUNBUFFERED 1
 ENV PYTHONPATH "/usr/local/bin/python"
 RUN mkdir /user_service
 WORKDIR /user_service
 RUN apt-get -y update
 RUN apt-get -y install curl wget make gcc build-essential
 RUN apt-get install -y python-dev
 RUN apt-get install -y supervisor
 RUN apt-get install -y nginx
 RUN pip install gunicorn
 RUN pip install setproctitle
 ADD requirements.txt /user_service/
 RUN pip install -r requirements.txt 
 ADD . /user_service/
 COPY docker-entrypoint.sh /user_service/
 RUN chmod u+x docker-entrypoint.sh
 RUN chmod u+x bin/gunicorn_start  
 COPY user_service.conf /etc/nginx/sites-available/
 RUN ln -s /etc/nginx/sites-available/user_service.conf /etc/nginx/sites-enabled
 COPY user_service_supervisor.conf  /etc/supervisor/conf.d/
 RUN mkdir /root/.aws/
 COPY config /root/.aws/config
 COPY credentials /root/.aws/credentials
 EXPOSE 80
 RUN mkdir -p /user_service/logs
 RUN mkdir -p /static
 RUN mkdir -p /user_service/static
 RUN chmod -R 777 /static
 RUN touch /user_service/logs/gunicorn_supervisor.log
 RUN python manage.py migrate
 ENTRYPOINT ["bash", "/user_service/docker-entrypoint.sh"]
 
