FROM faizanscuelogic/python-2.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /accounts
WORKDIR /accounts
RUN apt-get -y update
RUN apt-get -y install curl wget make gcc build-essential
RUN apt-get install -y python-dev
RUN apt-get install -y supervisor
RUN apt-get install -y nginx
RUN pip install gunicorn
RUN pip install setproctitle
ADD requirements.txt /accounts/
RUN pip install -r requirements.txt
ADD . /accounts/
COPY docker-entrypoint.sh /accounts/
RUN chmod u+x docker-entrypoint.sh
RUN chmod u+x bin/gunicorn_start  
COPY accounts.conf /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/accounts.conf /etc/nginx/sites-enabled
COPY accounts_supervisor.conf  /etc/supervisor/conf.d/
EXPOSE 80
RUN mkdir -p /accounts/logs
RUN mkdir -p /static
RUN mkdir -p /accounts/static
RUN chmod -R 777 /static
RUN touch /accounts/logs/gunicorn_supervisor.log
RUN python manage.py migrate
ENTRYPOINT ["bash", "/accounts/docker-entrypoint.sh"]
